import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import chatRouter from "./chat";
import packagesRouter from "./packages";
import subscriptionsRouter from "./subscriptions";
import paymentsRouter from "./payments";
import couponsRouter from "./coupons";
import consultationsRouter from "./consultations";
import faqsRouter from "./faqs";
import serviceAreasRouter from "./service-areas";
import adminRouter from "./admin";
import knowledgeRouter from "./knowledge";
import auditLogRouter from "./audit-log";
import notificationsRouter from "./notifications";
import contractAnalysisRouter from "./contract-analysis";
import telegramRouter from "./telegram";
import telegramSyncRouter from "./telegram-sync";
import platformSettingsRouter from "./platform-settings";
import quotaRouter from "./quota";
import contactRouter from "./contact";
import mojCircularsRouter from "./moj-circulars";
import legalCodexRouter from "./legal-codex";
import communityInitiativesRouter from "./community-initiatives";
import whatsappAdminRouter from "./whatsapp-admin";
import { topicRouterRouter } from "./topic-router";
import organizationsRouter from "./organizations";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(chatRouter);
router.use(packagesRouter);
router.use(subscriptionsRouter);
router.use(paymentsRouter);
router.use(couponsRouter);
router.use(consultationsRouter);
router.use(faqsRouter);
router.use(serviceAreasRouter);
router.use(adminRouter);
router.use(knowledgeRouter);
router.use(auditLogRouter);
router.use(notificationsRouter);
router.use(contractAnalysisRouter);
router.use(telegramRouter);
router.use(telegramSyncRouter);
router.use(platformSettingsRouter);
router.use(quotaRouter);
router.use(contactRouter);
router.use(mojCircularsRouter);
router.use(legalCodexRouter);
router.use(communityInitiativesRouter);
router.use(whatsappAdminRouter);
router.use(topicRouterRouter);
router.use(organizationsRouter);

export default router;
