import { Route, Switch, Router as WouterRouter, useLocation, Redirect } from 'wouter';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ArrowRight } from 'lucide-react';
import { useEffect, useRef } from 'react';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import { AuthProvider } from '@/hooks/use-auth';
import { LangProvider, useLang } from '@/hooks/use-language';
import { ThemeProvider } from '@/hooks/use-theme';
import { ProtectedRoute, GuestOnlyRoute } from '@/components/protected-route';